// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// The request message for the `ListTraces` method. All fields are required
/// unless specified.
public struct ListTracesRequest: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. ID of the Cloud project where the trace data is stored.
  public var projectId: Swift.String = Swift.String()

  /// Optional. Type of data returned for traces in the list. Default is
  /// `MINIMAL`.
  public var view: ListTracesRequest.ViewType = ListTracesRequest.ViewType()

  /// Optional. Maximum number of traces to return. If not specified or <= 0, the
  /// implementation selects a reasonable value.  The implementation may
  /// return fewer traces than the requested page size.
  public var pageSize: Swift.Int32 = Swift.Int32()

  /// Token identifying the page of results to return. If provided, use the
  /// value of the `next_page_token` field from a previous request.
  public var pageToken: Swift.String = Swift.String()

  /// Start of the time interval (inclusive) during which the trace data was
  /// collected from the application.
  public var startTime: GoogleWKT.WKTTimestamp? = nil

  /// End of the time interval (inclusive) during which the trace data was
  /// collected from the application.
  public var endTime: GoogleWKT.WKTTimestamp? = nil

  /// Optional. A filter against labels for the request.
  ///
  /// By default, searches use prefix matching. To specify exact match, prepend
  /// a plus symbol (`+`) to the search term.
  /// Multiple terms are ANDed. Syntax:
  ///
  /// *   `root:NAME_PREFIX` or `NAME_PREFIX`: Return traces where any root
  ///     span starts with `NAME_PREFIX`.
  /// *   `+root:NAME` or `+NAME`: Return traces where any root span's name is
  ///     exactly `NAME`.
  /// *   `span:NAME_PREFIX`: Return traces where any span starts with
  ///     `NAME_PREFIX`.
  /// *   `+span:NAME`: Return traces where any span's name is exactly
  ///     `NAME`.
  /// *   `latency:DURATION`: Return traces whose overall latency is
  ///     greater or equal to than `DURATION`. Accepted units are nanoseconds
  ///     (`ns`), milliseconds (`ms`), and seconds (`s`). Default is `ms`. For
  ///     example, `latency:24ms` returns traces whose overall latency
  ///     is greater than or equal to 24 milliseconds.
  /// *   `label:LABEL_KEY`: Return all traces containing the specified
  ///     label key (exact match, case-sensitive) regardless of the key:value
  ///     pair's value (including empty values).
  /// *   `LABEL_KEY:VALUE_PREFIX`: Return all traces containing the specified
  ///     label key (exact match, case-sensitive) whose value starts with
  ///     `VALUE_PREFIX`. Both a key and a value must be specified.
  /// *   `+LABEL_KEY:VALUE`: Return all traces containing a key:value pair
  ///     exactly matching the specified text. Both a key and a value must be
  ///     specified.
  /// *   `method:VALUE`: Equivalent to `/http/method:VALUE`.
  /// *   `url:VALUE`: Equivalent to `/http/url:VALUE`.
  public var filter: Swift.String = Swift.String()

  /// Optional. Field used to sort the returned traces.
  /// Can be one of the following:
  ///
  /// *   `trace_id`
  /// *   `name` (`name` field of root span in the trace)
  /// *   `duration` (difference between `end_time` and `start_time` fields of
  ///      the root span)
  /// *   `start` (`start_time` field of the root span)
  ///
  /// Descending order can be specified by appending `desc` to the sort field
  /// (for example, `name desc`).
  ///
  /// Only one sort field is permitted.
  public var orderBy: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ListTracesRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ListTracesRequest().with { $0.projectId = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let projectId = CodingKeys(stringValue: "projectId")
    static let view = CodingKeys(stringValue: "view")
    static let pageSize = CodingKeys(stringValue: "pageSize")
    static let pageToken = CodingKeys(stringValue: "pageToken")
    static let startTime = CodingKeys(stringValue: "startTime")
    static let endTime = CodingKeys(stringValue: "endTime")
    static let filter = CodingKeys(stringValue: "filter")
    static let orderBy = CodingKeys(stringValue: "orderBy")

    static let _knownKeys: Set<Swift.String> = [
      "projectId",
      "view",
      "pageSize",
      "pageToken",
      "startTime",
      "endTime",
      "filter",
      "orderBy",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .projectId) {
      self.projectId = value
    }
    if let value = try container.decodeIfPresent(ListTracesRequest.ViewType.self, forKey: .view) {
      self.view = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .pageSize) {
      self.pageSize = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .pageToken) {
      self.pageToken = value
    }
    self.startTime = try container.decodeIfPresent(GoogleWKT.WKTTimestamp.self, forKey: .startTime)
    self.endTime = try container.decodeIfPresent(GoogleWKT.WKTTimestamp.self, forKey: .endTime)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .filter) {
      self.filter = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .orderBy) {
      self.orderBy = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.projectId, forKey: .projectId)
    try container.encode(self.view, forKey: .view)
    try container.encode(self.pageSize, forKey: .pageSize)
    try container.encode(self.pageToken, forKey: .pageToken)
    try container.encodeIfPresent(self.startTime, forKey: .startTime)
    try container.encodeIfPresent(self.endTime, forKey: .endTime)
    try container.encode(self.filter, forKey: .filter)
    try container.encode(self.orderBy, forKey: .orderBy)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Type of data returned for traces in the list.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum ViewType: Codable, Equatable, Sendable {
    /// Default is `MINIMAL` if unspecified.
    case unspecified
    /// Minimal view of the trace record that contains only the project
    /// and trace IDs.
    case minimal
    /// Root span view of the trace record that returns the root spans along
    /// with the minimal trace data.
    case rootspan
    /// Complete view of the trace record that contains the actual trace data.
    /// This is equivalent to calling the REST `get` or RPC `GetTrace` method
    /// using the ID of each listed trace.
    case complete
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .minimal: return 1
      case .rootspan: return 2
      case .complete: return 3
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "VIEW_TYPE_UNSPECIFIED"
      case .minimal: return "MINIMAL"
      case .rootspan: return "ROOTSPAN"
      case .complete: return "COMPLETE"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:ViewType/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "VIEW_TYPE_UNSPECIFIED": self = .unspecified
      case "MINIMAL": self = .minimal
      case "ROOTSPAN": self = .rootspan
      case "COMPLETE": self = .complete
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:ViewType/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .minimal
      case 2: self = .rootspan
      case 3: self = .complete
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("VIEW_TYPE_UNSPECIFIED")
      case .minimal: return try container.encode("MINIMAL")
      case .rootspan: return try container.encode("ROOTSPAN")
      case .complete: return try container.encode("COMPLETE")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.devtools.cloudtrace.v1.ListTracesRequest"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
