// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWkt
@_spi(GoogleCloudInternal) import GoogleCloudGax

extension Clients {
  class TraceServiceTransport: TraceServiceStub {
    let inner: GoogleCloudGax._HTTPClient

    public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
      self.inner = try GoogleCloudGax._HTTPClient(
        from: options,
        withDefaultEndpoint: "https://cloudtrace.googleapis.com",
      )
    }

    public func listTraces(
      request: ListTracesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudTraceV1.ListTracesResponse {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.projectId as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.project_id' is not set or is empty")
        }
        return "/v1/projects/\(pathVariable0)/traces"
      }()
      var query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      let encoder = GoogleCloudGax.QueryParameterEncoder()
      query.append(contentsOf: try encoder.encode(request.view, prefix: "view"))
      query.append(contentsOf: try encoder.encode(request.pageSize, prefix: "pageSize"))
      query.append(contentsOf: try encoder.encode(request.pageToken, prefix: "pageToken"))
      query.append(contentsOf: try encoder.encode(request.startTime, prefix: "startTime"))
      query.append(contentsOf: try encoder.encode(request.endTime, prefix: "endTime"))
      query.append(contentsOf: try encoder.encode(request.filter, prefix: "filter"))
      query.append(contentsOf: try encoder.encode(request.orderBy, prefix: "orderBy"))
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.GET)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      return try await req.rpc(
        GoogleCloudTraceV1.ListTracesResponse.self, timeout: options.attemptTimeout
      ).get()
    }

    public func getTrace(
      request: GetTraceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudTraceV1.Trace {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.projectId as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.project_id' is not set or is empty")
        }
        guard let pathVariable1 = request.traceId as Swift.String?, !pathVariable1.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.trace_id' is not set or is empty")
        }
        return "/v1/projects/\(pathVariable0)/traces/\(pathVariable1)"
      }()
      let query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.GET)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      return try await req.rpc(
        GoogleCloudTraceV1.Trace.self, timeout: options.attemptTimeout
      ).get()
    }

    public func patchTraces(
      request: PatchTracesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.projectId as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.project_id' is not set or is empty")
        }
        return "/v1/projects/\(pathVariable0)/traces"
      }()
      let query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      var req = try await self.inner.newRequest(path: path, query: query)
      req.setMethod(.PATCH)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      if let body = request.traces {
        req.setBody(data: try JSONEncoder().encode(body), ofContentType: "application/json")
      }
      _ = try await req.rpc(
        GoogleCloudWkt.Empty.self, timeout: options.attemptTimeout
      ).get()
    }
  }
}
