// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWkt
import GoogleCloudGax

/// This file describes an API for collecting and viewing traces and spans
/// within a trace.  A Trace is a collection of spans corresponding to a single
/// operation or set of operations for an application. A span is an individual
/// timed event which forms a node of the trace tree. Spans for a single trace
/// may span multiple services.
///
/// @Snippet(path: "TraceServiceQuickstart")
public class TraceServiceClient: Clients.TraceServiceProtocol {
  let inner: any Clients.TraceServiceStub

  /// Creates a new `TraceServiceClient` instance.
  public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
    var inner: any Clients.TraceServiceStub = try Clients.TraceServiceTransport(options)
    inner = Clients.TraceServiceRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.TraceServiceLogging(inner, logger: logger)
    }
    self.inner = inner
  }

  /// Returns of a list of traces that match the specified filter conditions.
  ///
  /// @Snippet(path: "TraceService_ListTraces")
  public func listTraces(
    request: ListTracesRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudTraceV1.ListTracesResponse {
    try await self.inner.listTraces(request: request, options: options)
  }

  /// Returns of a list of traces that match the specified filter conditions.
  ///
  /// @Snippet(path: "TraceService_ListTraces")
  public func listTraces(
    byItem: ListTracesRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Trace, Swift.Error> {
    let listRpc = { (token: Swift.String) async throws -> GoogleCloudTraceV1.ListTracesResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listTraces(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Gets a single trace by its ID.
  ///
  /// @Snippet(path: "TraceService_GetTrace")
  public func getTrace(
    request: GetTraceRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudTraceV1.Trace {
    try await self.inner.getTrace(request: request, options: options)
  }

  /// Sends new traces to Stackdriver Trace or updates existing traces. If the ID
  /// of a trace that you send matches that of an existing trace, any fields
  /// in the existing trace and its spans are overwritten by the provided values,
  /// and any new fields provided are merged with the existing trace data. If the
  /// ID does not match, a new trace is created.
  ///
  /// @Snippet(path: "TraceService_PatchTraces")
  public func patchTraces(
    request: PatchTracesRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    try await self.inner.patchTraces(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `TraceServiceClient`.
  ///
  /// To mock `TraceServiceClient` change your functions to receive
  /// `some TraceServiceProtocol` or `any TraceServiceProtocol`
  /// and pass a mock implementation in your tests.
  public protocol TraceServiceProtocol {
    /// See `TraceServiceClient.listTraces`.
    func listTraces(request: ListTracesRequest) async throws
      -> GoogleCloudTraceV1.ListTracesResponse

    /// See `TraceServiceClient.listTraces`.
    func listTraces(
      byItem: ListTracesRequest
    ) throws -> any AsyncSequence<Trace, Swift.Error>

    /// See `TraceServiceClient.listTraces`.
    func listTraces(
      projectId: Swift.String,
    ) throws -> any AsyncSequence<Trace, Swift.Error>

    /// See `TraceServiceClient.getTrace`.
    func getTrace(request: GetTraceRequest) async throws -> GoogleCloudTraceV1.Trace

    /// See `TraceServiceClient.getTrace`.
    func getTrace(
      projectId: Swift.String,
      traceId: Swift.String,
    ) async throws -> GoogleCloudTraceV1.Trace

    /// See `TraceServiceClient.patchTraces`.
    func patchTraces(request: PatchTracesRequest) async throws

    /// See `TraceServiceClient.patchTraces`.
    func patchTraces(
      projectId: Swift.String,
      traces: Traces?,
    ) async throws

    /// See `TraceServiceClient.listTraces`.
    func listTraces(
      request: ListTracesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudTraceV1.ListTracesResponse

    /// See `TraceServiceClient.listTraces`.
    func listTraces(
      byItem: ListTracesRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<Trace, Swift.Error>

    /// See `TraceServiceClient.getTrace`.
    func getTrace(
      request: GetTraceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudTraceV1.Trace

    /// See `TraceServiceClient.patchTraces`.
    func patchTraces(
      request: PatchTracesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws
  }
}

// Default implementations
extension Clients.TraceServiceProtocol {
  public func listTraces(request: ListTracesRequest) async throws
    -> GoogleCloudTraceV1.ListTracesResponse
  {
    try await self.listTraces(request: request, options: .init())
  }

  public func listTraces(
    request: ListTracesRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudTraceV1.ListTracesResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listTraces(
    byItem: ListTracesRequest
  ) throws -> any AsyncSequence<Trace, Swift.Error> {
    try self.listTraces(byItem: byItem, options: .init())
  }

  public func listTraces(
    byItem: ListTracesRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Trace, Swift.Error> {
    let listRpc = { (token: Swift.String) async throws -> GoogleCloudTraceV1.ListTracesResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listTraces(
    projectId: Swift.String,
  ) throws -> any AsyncSequence<Trace, Swift.Error> {
    let request = ListTracesRequest().with {
      $0.projectId = projectId
    }
    return try self.listTraces(byItem: request)
  }

  public func getTrace(request: GetTraceRequest) async throws -> GoogleCloudTraceV1.Trace {
    try await self.getTrace(request: request, options: .init())
  }

  public func getTrace(
    request: GetTraceRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudTraceV1.Trace {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getTrace(
    projectId: Swift.String,
    traceId: Swift.String,
  ) async throws -> GoogleCloudTraceV1.Trace {
    let request = GetTraceRequest().with {
      $0.projectId = projectId
      $0.traceId = traceId
    }
    return try await self.getTrace(request: request)
  }

  public func patchTraces(request: PatchTracesRequest) async throws {
    try await self.patchTraces(request: request, options: .init())
  }

  public func patchTraces(
    request: PatchTracesRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func patchTraces(
    projectId: Swift.String,
    traces: Traces?,
  ) async throws {
    let request = PatchTracesRequest().with {
      $0.projectId = projectId
      $0.traces = traces
    }
    try await self.patchTraces(request: request)
  }
}
