// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWKT
import GoogleCloudGax
import struct Logging.Logger

extension Clients {
  final class TraceServiceLogging: TraceServiceStub {
    let inner: any TraceServiceStub
    let logger: Logger

    public init(_ inner: any TraceServiceStub, logger: Logger) {
      var logger = logger
      logger[metadataKey: "gcp.artifact.id"] = "google-devtools-cloudtrace-v1"
      logger[metadataKey: "gcp.client.service"] = "cloudtrace"
      logger[metadataKey: "gcp.experimental.swift.client"] = "TraceService"
      self.inner = inner
      self.logger = logger
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleCloudGax.RequestOptions,
      name: Swift.String,
      action: (Input, GoogleCloudGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      var logger = logger
      logger[metadataKey: "gcp.experimental.swift.request.id"] = "\(UUID())"
      logger[metadataKey: "gcp.experimental.swift.method"] = .string(name)
      logger.debug("enter  : \(request) \(options)")
      do {
        let output = try await action(request, options)
        logger.debug("success: \(request) \(options) \(output)")
        return output
      } catch let error {
        logger.debug("error  : \(request) \(options) \(error)")
        throw error
      }
    }

    public func listTraces(
      request: ListTracesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudTraceV1.ListTracesResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listTraces",
        action: {
          (r: ListTracesRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudTraceV1.ListTracesResponse
          in
          return try await self.inner.listTraces(request: r, options: o)
        })
    }

    public func getTrace(
      request: GetTraceRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudTraceV1.Trace {
      try await self._intercept(
        request: request,
        options: options,
        name: "getTrace",
        action: {
          (r: GetTraceRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudTraceV1.Trace
          in
          return try await self.inner.getTrace(request: r, options: o)
        })
    }

    public func patchTraces(
      request: PatchTracesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "patchTraces",
        action: { (r: PatchTracesRequest, o: GoogleCloudGax.RequestOptions) async throws -> Void in
          return try await self.inner.patchTraces(request: r, options: o)
        })
    }
  }
}
