// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// A span represents a single timed event within a trace. Spans can be nested
/// and form a trace tree. Often, a trace contains a root span that describes the
/// end-to-end latency of an operation and, optionally, one or more subspans for
/// its suboperations. Spans do not need to be contiguous. There may be gaps
/// between spans in a trace.
public struct TraceSpan: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Identifier for the span. Must be a 64-bit integer other than 0 and
  /// unique within a trace. For example, `2205310701640571284`.
  public var spanId: Swift.UInt64 = Swift.UInt64()

  /// Distinguishes between spans generated in a particular context. For example,
  /// two spans with the same name may be distinguished using `RPC_CLIENT`
  /// and `RPC_SERVER` to identify queueing latency associated with the span.
  public var kind: TraceSpan.SpanKind = TraceSpan.SpanKind()

  /// Name of the span. Must be less than 128 bytes. The span name is sanitized
  /// and displayed in the Stackdriver Trace tool in the
  /// Google Cloud Platform Console.
  /// The name may be a method name or some other per-call site name.
  /// For the same executable and the same call point, a best practice is
  /// to use a consistent name, which makes it easier to correlate
  /// cross-trace spans.
  public var name: Swift.String = Swift.String()

  /// Start time of the span in nanoseconds from the UNIX epoch.
  public var startTime: GoogleCloudWkt.Timestamp? = nil

  /// End time of the span in nanoseconds from the UNIX epoch.
  public var endTime: GoogleCloudWkt.Timestamp? = nil

  /// Optional. ID of the parent span, if any.
  public var parentSpanId: Swift.UInt64 = Swift.UInt64()

  /// Collection of labels associated with the span. Label keys must be less than
  /// 128 bytes. Label values must be less than 16 kilobytes (10MB for
  /// `/stacktrace` values).
  ///
  /// Some predefined label keys exist, or you may create your own. When creating
  /// your own, we recommend the following formats:
  ///
  /// * `/category/product/key` for agents of well-known products (e.g.
  ///   `/db/mongodb/read_size`).
  /// * `short_host/path/key` for domain-specific keys (e.g.
  ///   `foo.com/myproduct/bar`)
  ///
  /// Predefined labels include:
  ///
  /// *   `/agent`
  /// *   `/component`
  /// *   `/error/message`
  /// *   `/error/name`
  /// *   `/http/client_city`
  /// *   `/http/client_country`
  /// *   `/http/client_protocol`
  /// *   `/http/client_region`
  /// *   `/http/host`
  /// *   `/http/method`
  /// *   `/http/path`
  /// *   `/http/redirected_url`
  /// *   `/http/request/size`
  /// *   `/http/response/size`
  /// *   `/http/route`
  /// *   `/http/status_code`
  /// *   `/http/url`
  /// *   `/http/user_agent`
  /// *   `/pid`
  /// *   `/stacktrace`
  /// *   `/tid`
  public var labels: [Swift.String: Swift.String] = [:]

  /// Initialize a new instance of `TraceSpan`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = TraceSpan().with { $0.spanId = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Type of span. Can be used to specify additional relationships between spans
  /// in addition to a parent/child relationship.
  public enum SpanKind: Codable, Equatable, Sendable {
    /// Unspecified.
    case unspecified
    /// Indicates that the span covers server-side handling of an RPC or other
    /// remote network request.
    case rpcServer
    /// Indicates that the span covers the client-side wrapper around an RPC or
    /// other remote request.
    case rpcClient
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .rpcServer: return 1
      case .rpcClient: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "SPAN_KIND_UNSPECIFIED"
      case .rpcServer: return "RPC_SERVER"
      case .rpcClient: return "RPC_CLIENT"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:SpanKind/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "SPAN_KIND_UNSPECIFIED": self = .unspecified
      case "RPC_SERVER": self = .rpcServer
      case "RPC_CLIENT": self = .rpcClient
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:SpanKind/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .rpcServer
      case 2: self = .rpcClient
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .rpcServer: return try container.encode(1)
      case .rpcClient: return try container.encode(2)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.devtools.cloudtrace.v1.TraceSpan"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
